apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: classrooms
        image: ushna1923/scd-final-lab-exam-ushna-nadeem-classrooms:latest
        ports:
        - containerPort: 3226
