apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ushna1923/scd-final-lab-exam-ushna-nadeem-auth:latest
        ports:
        - containerPort: 3225
