apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: ushna1923/scd-final-lab-exam-ushna-nadeem-post:latest
        ports:
        - containerPort: 3228
