apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - name: images
        image: ushna1923/scd-final-lab-exam-ushna-nadeem-images:latest
        ports:
        - containerPort: 8080
